name = "loklog"
compatibility_date = "2025-12-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" 
database_name = "loklog-db"
database_id = "1493be62-4921-4882-9541-cc57f079a14c"

